// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: picto_stick

#ifndef _PICTO_STICK_UI_H
#define _PICTO_STICK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_pictoprev;
extern lv_obj_t * ui_pictonow;
extern lv_obj_t * ui_pictonext;
extern lv_obj_t * ui_naamLBL;
extern lv_obj_t * ui_tijdLBL;
extern lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_aankleden_png);    // assets/aankleden.png
LV_IMG_DECLARE(ui_img_douchen_png);    // assets/douchen.png
LV_IMG_DECLARE(ui_img_avondmaal_png);    // assets/avondmaal.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
