// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: pictodevice_ui

#include "ui.h"

void ui_ScreenMAIN240x135_screen_init(void)
{
    ui_ScreenMAIN240x135 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMAIN240x135, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
