// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: pictodevice_ui

#include "ui.h"

void ui_ScreenMAIN240x135_screen_init(void)
{
    ui_ScreenMAIN240x135 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMAIN240x135, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tijdvakMorningLBL = lv_label_create(ui_ScreenMAIN240x135);
    lv_obj_set_width(ui_tijdvakMorningLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tijdvakMorningLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tijdvakMorningLBL, -77);
    lv_obj_set_y(ui_tijdvakMorningLBL, 47);
    lv_obj_set_align(ui_tijdvakMorningLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tijdvakMorningLBL, "-------");

    ui_Label2 = lv_label_create(ui_ScreenMAIN240x135);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -15);
    lv_obj_set_y(ui_Label2, 46);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_ScreenMAIN240x135);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 55);
    lv_obj_set_y(ui_Label3, 47);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);

}
