
#include "_locale.h"
#include <Arduino.h>

// WIFI
const char *TXT_WIFI_EXCELLENT     = "Uitstekend";
const char *TXT_WIFI_GOOD          = "Goed";
const char *TXT_WIFI_FAIR          = "Redelijk";
const char *TXT_WIFI_WEAK          = "Zwak";
const char *TXT_WIFI_NO_CONNECTION = "Geen Verbinding";

// WIFI STATUS
const char *TXT_WL_NO_SHIELD       = "No Shield";
const char *TXT_WL_IDLE_STATUS     = "Idle";
const char *TXT_WL_NO_SSID_AVAIL   = "No SSID Available";
const char *TXT_WL_SCAN_COMPLETED  = "Scan Complete";
const char *TXT_WL_CONNECTED       = "Connected";
const char *TXT_WL_CONNECT_FAILED  = "Connection Failed";
const char *TXT_WL_CONNECTION_LOST = "Connection Lost";
const char *TXT_WL_DISCONNECTED    = "Disconnected";

// WIFI MANAGER
const char *TXT_WM_WEBPORTAL_STARTED = "Webportaal gestart op: ";
const char *TXT_WM_CONNECT_SSID = "verbind met WiFi SSID: ";
const char *TXT_WM_WITH_PASSWORD = "met wachtwoord 'password' om WiFi";
const char *TXT_WM_CONFIG_DEVICE = "voor dit apparaat te configureren.";