#include "_locale.h"
#include <Arduino.h>

// WIFI
const char *TXT_WIFI_EXCELLENT     = "Excellent";
const char *TXT_WIFI_GOOD          = "Good";
const char *TXT_WIFI_FAIR          = "Fair";
const char *TXT_WIFI_WEAK          = "Weak";
const char *TXT_WIFI_NO_CONNECTION = "No Connection";

// WIFI STATUS
const char *TXT_WL_NO_SHIELD       = "No Shield";
const char *TXT_WL_IDLE_STATUS     = "Idle";
const char *TXT_WL_NO_SSID_AVAIL   = "No SSID Available";
const char *TXT_WL_SCAN_COMPLETED  = "Scan Complete";
const char *TXT_WL_CONNECTED       = "Connected";
const char *TXT_WL_CONNECT_FAILED  = "Connection Failed";
const char *TXT_WL_CONNECTION_LOST = "Connection Lost";
const char *TXT_WL_DISCONNECTED    = "Disconnected";

// WIFI MANAGER
const char *TXT_WM_WEBPORTAL_STARTED = "Webportal started at: ";
const char *TXT_WM_CONNECT_SSID = "please connect to WiFi SSID: ";
const char *TXT_WM_WITH_PASSWORD = "with password 'password' to";
const char *TXT_WM_CONFIG_DEVICE = "configure WiFI for this device.";