// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: pictodevice_ui

#include "ui.h"

void ui_ScreenMAIN_screen_init(void)
{
    ui_ScreenMAIN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMAIN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMAIN, lv_color_hex(0xCFCDCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMAIN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btimeslotMorningLBL = lv_label_create(ui_ScreenMAIN);
    lv_obj_set_width(ui_btimeslotMorningLBL, lv_pct(30));
    lv_obj_set_height(ui_btimeslotMorningLBL, lv_pct(6));
    lv_obj_set_x(ui_btimeslotMorningLBL, -101);
    lv_obj_set_y(ui_btimeslotMorningLBL, 83);
    lv_obj_set_align(ui_btimeslotMorningLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btimeslotMorningLBL, "");
    lv_obj_set_style_bg_color(ui_btimeslotMorningLBL, lv_color_hex(0xB3E5FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btimeslotMorningLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btimeslotAfternoonLBL = lv_label_create(ui_ScreenMAIN);
    lv_obj_set_width(ui_btimeslotAfternoonLBL, lv_pct(30));
    lv_obj_set_height(ui_btimeslotAfternoonLBL, lv_pct(6));
    lv_obj_set_x(ui_btimeslotAfternoonLBL, -2);
    lv_obj_set_y(ui_btimeslotAfternoonLBL, 83);
    lv_obj_set_align(ui_btimeslotAfternoonLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btimeslotAfternoonLBL, "");
    lv_obj_set_style_bg_color(ui_btimeslotAfternoonLBL, lv_color_hex(0xA5D6A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btimeslotAfternoonLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btimeslotEveningLBL = lv_label_create(ui_ScreenMAIN);
    lv_obj_set_width(ui_btimeslotEveningLBL, lv_pct(30));
    lv_obj_set_height(ui_btimeslotEveningLBL, lv_pct(6));
    lv_obj_set_x(ui_btimeslotEveningLBL, 97);
    lv_obj_set_y(ui_btimeslotEveningLBL, 83);
    lv_obj_set_align(ui_btimeslotEveningLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btimeslotEveningLBL, "");
    lv_obj_set_style_bg_color(ui_btimeslotEveningLBL, lv_color_hex(0xFFE082), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btimeslotEveningLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPNL = lv_obj_create(ui_ScreenMAIN);
    lv_obj_set_width(ui_nowPNL, 100);
    lv_obj_set_height(ui_nowPNL, 100);
    lv_obj_set_x(ui_nowPNL, 0);
    lv_obj_set_y(ui_nowPNL, -9);
    lv_obj_set_align(ui_nowPNL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_nowPNL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_nowPNL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPNL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_prevPNL = lv_obj_create(ui_ScreenMAIN);
    lv_obj_set_width(ui_prevPNL, 100);
    lv_obj_set_height(ui_prevPNL, 100);
    lv_obj_set_x(ui_prevPNL, -103);
    lv_obj_set_y(ui_prevPNL, -9);
    lv_obj_set_align(ui_prevPNL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_prevPNL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_prevPNL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_prevPNL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextPNL = lv_obj_create(ui_ScreenMAIN);
    lv_obj_set_width(ui_nextPNL, 100);
    lv_obj_set_height(ui_nextPNL, 100);
    lv_obj_set_x(ui_nextPNL, 103);
    lv_obj_set_y(ui_nextPNL, -9);
    lv_obj_set_align(ui_nextPNL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_nextPNL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_nextPNL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nextPNL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
