// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: pictodevice_ui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenMAIN
void ui_ScreenMAIN_screen_init(void);
lv_obj_t * ui_ScreenMAIN;
lv_obj_t * ui_btimeslotMorningLBL;
lv_obj_t * ui_btimeslotAfternoonLBL;
lv_obj_t * ui_btimeslotEveningLBL;
lv_obj_t * ui_nowPNL;
lv_obj_t * ui_prevPNL;
lv_obj_t * ui_nextPNL;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSPLASH
void ui_ScreenSPLASH_screen_init(void);
lv_obj_t * ui_ScreenSPLASH;
lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenMAIN_screen_init();
    ui_ScreenSPLASH_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenMAIN);
}
