// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: pictodevice_ui

#ifndef _PICTODEVICE_UI_UI_H
#define _PICTODEVICE_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenMAIN
void ui_ScreenMAIN_screen_init(void);
extern lv_obj_t * ui_ScreenMAIN;
extern lv_obj_t * ui_btimeslotMorningLBL;
extern lv_obj_t * ui_btimeslotAfternoonLBL;
extern lv_obj_t * ui_btimeslotEveningLBL;
extern lv_obj_t * ui_nowPNL;
extern lv_obj_t * ui_prevPNL;
extern lv_obj_t * ui_nextPNL;
extern lv_obj_t * ui_nowIMG;
extern lv_obj_t * ui_nextIMG;
extern lv_obj_t * ui_prevIMG;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_shopping_cart_24dp_1f1f1f_fill0_wght400_grad0_opsz24_png);    // assets/shopping_cart_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_sledding_24dp_1f1f1f_fill0_wght400_grad0_opsz24_png);    // assets/sledding_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_hotel_24dp_1f1f1f_fill0_wght400_grad0_opsz24_png);    // assets/hotel_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
