// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: picto_stick

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pictoprev = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_pictoprev, &ui_img_aankleden_png);
    lv_obj_set_width(ui_pictoprev, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_pictoprev, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_pictoprev, -111);
    lv_obj_set_y(ui_pictoprev, -10);
    lv_obj_set_align(ui_pictoprev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pictoprev, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pictoprev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_pictoprev, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pictonow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_pictonow, &ui_img_douchen_png);
    lv_obj_set_width(ui_pictonow, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_pictonow, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_pictonow, 0);
    lv_obj_set_y(ui_pictonow, -10);
    lv_obj_set_align(ui_pictonow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pictonow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pictonow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pictonext = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_pictonext, &ui_img_avondmaal_png);
    lv_obj_set_width(ui_pictonext, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_pictonext, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_pictonext, 113);
    lv_obj_set_y(ui_pictonext, -10);
    lv_obj_set_align(ui_pictonext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pictonext, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pictonext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_naamLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_naamLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_naamLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_naamLBL, -94);
    lv_obj_set_y(ui_naamLBL, 54);
    lv_obj_set_align(ui_naamLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_naamLBL, "Peter");

    ui_tijdLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tijdLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tijdLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tijdLBL, -44);
    lv_obj_set_y(ui_tijdLBL, 54);
    lv_obj_set_align(ui_tijdLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tijdLBL, "13:45");

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 114);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 48);
    lv_obj_set_y(ui_Bar1, 54);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

}
